課題提出 OTA88 第3章
daimyo-college/ruby-super-intro-lesson pull request #41
Opened 2019-06-24 11:12 UTC by OTA88

続いて、3章です。

2019-06-26 06:31 UTC, udzura commented on OTA88/chapter3/3-5.rb
> +when season = "春"
おっと、 when の後ろは代入しません。
なので単に `when "春"` です。
`when season == "春"` でも大丈夫ですが、今回は前者の意図かなと思います

2019-06-26 06:31 UTC, udzura commented on OTA88/chapter3/3-5.rb
> +when season = "夏"
ここもですね

2019-06-26 06:31 UTC, udzura requested changes
一問だけ気になりました！

2019-06-30 10:12 UTC, OTA88 commented on OTA88/chapter3/3-5.rb
> +when season = "春"
`when season == "春"`のつもりで、`season = "春"`と書いちゃってました。。

2019-06-30 10:13 UTC, OTA88 commented on OTA88/chapter3/3-5.rb
> +when season = "夏"
orz...

2019-06-30 10:27 UTC, OTA88 commented
修正ファイルをpushしました。一点質問させてください。

ファイルの中で、指摘を受けた古いコードをコメントアウトしたのですが、
余計な文字はファイル中に残さない方が良いのでしょうか？

つか、そもそもここで質問しない方が良いのでしょうか？
（質問はslackでやった方が良い？？）

2019-06-30 11:34 UTC, june29 commented
@udzura さんの同僚で、コードレビューのお手伝いをしている者です。こんにちは！

>ファイルの中で、指摘を受けた古いコードをコメントアウトしたのですが、
>余計な文字はファイル中に残さない方が良いのでしょうか？

今回は特に Git で履歴をばっちり管理できているので、コメントアウトせずに消しちゃうのがよいと思います。もし業務で書くようなコードに「試行錯誤の途中のコード」や「以前の仕様のコード」がコメントアウトで残り続けて山積するとしたら、現役のコードがどんどん読みにくくなってしまいますよね。

Git で管理している限り、いつでもすべての履歴にアクセスできるので、安心して消していくとよいでしょう。

> つか、そもそもここで質問しない方が良いのでしょうか？
> （質問はslackでやった方が良い？？）

ぼくは、コードに関する会話は Pull Request 上でどんどんやっていくのがよいと考えます。コードから遠いところで会話すると「で、実際のコードはどうなっているの？」と遠回りになることがちょくちょくあるからです。今回のケースでは、実際にどんなコードをコメントアウトしているのかがすぐにわかったので、こうして回答しやすくなっています。

もうちょっと言うと、質問しないよりは質問する方が圧倒的によいので、どこに書くのが正解かを気にしすぎて身動きが取れなくなるくらいなら、今回みたいに気軽に書いてもらうのがよいと思います。それで「こういう場合は、こうするとベターですね」となれば、次回からそうすればいいですもんね :ok_hand:

2019-07-09 05:54 UTC, udzura commented
一言でいうと、「どこをどう変えたかの情報はGitで持ってるので、コメントで残すのは基本不要です」！
質問はどこでしてもいいです！

2019-07-09 05:54 UTC, udzura approved these changes
修正は 🆗 です！
今後はズバッと消しちゃってくださいませ〜

2019-07-09 05:54 UTC, merged

2019-07-21 05:59 UTC, OTA88 commented
@june29 さん初めまして。詳細にご回答頂きありがとうございます！共同作業の雰囲気が感じられて有り難いです！:)　これまで消すのが何となく怖かった&勿体無い気持ちもあったのですが、今後は大胆に消して行きます！

2019-07-21 06:01 UTC, june29 commented
お返事ありがとうございます、ぜひぜひ楽しみながら進めてみてください :hugs: