課題提出 ONO 第2章〜第6章
daimyo-college/ruby-super-intro-lesson pull request #49
Opened 2019-06-25 00:39 UTC by S-LEES

直前になってしまい申し訳ありません。
宜しくお願いします！

2019-06-25 07:18 UTC, igaiga requested changes
たくさん解答していただきありがとうございます！コメントしたので対応お願いしますー！

2019-06-25 07:18 UTC, igaiga commented on ono/c3_practice.rb
> +if season = "夏"
ここ、 == ですね

2019-06-25 07:18 UTC, igaiga commented on ono/c3_practice.rb
> +    puts = "かき氷食べたい"
ここはこれだと表示されずにputs変数への代入になってしまいます。 🍨

2019-06-25 07:18 UTC, igaiga commented on ono/c3_practice.rb
> +when season ="春"
ここも==ですね。
それと、この場合は case season と書いた方がseasonと書く重複を減らせていいですね。 🍹

2019-06-25 07:18 UTC, igaiga commented on ono/c4_practice.rb
> +puts drinks[0,2]
これだと
コーヒー
カフェラテ
になってしまいますね。

2019-06-25 07:18 UTC, igaiga commented on ono/c4_practice.rb
> +p drinks2
ここはどの問題を解いていますか？

2019-06-25 07:18 UTC, igaiga commented on ono/c4_practice.rb
> +drinks3 = ["ティーラテ", "カフェラテ", "抹茶ラテ"]
ここはeachを使って表示してみてください。

2019-06-25 07:18 UTC, igaiga commented on ono/c5_practice.rb
> +puts ["大吉","中吉","小吉"].sample
これだと凶が出ないですね。（みんな幸せではある ⛩ ）

2019-06-25 07:18 UTC, igaiga commented on ono/c5_practice.rb
> +p result
これはどこの問題でしょう？

2019-06-25 07:18 UTC, igaiga commented on ono/c6_practice.rb
> +p menu[:caffee]
coffeeとcaffe_latteで、caffe_latteを取得してください。 ☕️

2019-06-25 07:18 UTC, igaiga commented on ono/c6_practice.rb
> +p menu["紅茶貼りませんか？"]
"紅茶はありませんか？" ⌨️

2019-06-25 07:18 UTC, igaiga commented on ono/c6_practice.rb
> +p hash
お！素晴らしい！ 🌟

2019-06-25 07:18 UTC, igaiga commented on ono/c6_practice.rb
> +    menu.each do |key,value|
ここ、インデントが右に一段ずれてますね。ここは先頭からスタートです。

2019-06-25 07:18 UTC, igaiga commented on ono/c5_practice.rb
> +"#{x*2}円"
ここインデントお願いします

2019-06-25 07:18 UTC, igaiga commented on ono/c3_practice.rb
> +    puts = "かき氷食べたい"
他も含めて、インデントのスペースは2つでお願いします！

2019-06-26 06:56 UTC, udzura commented
ONOさんは提出課題のファイル命名規約が指定された形式じゃないですね！

```
ruby-super-intro-lesson/<自分のGitHub ID>/chapter<番号>/<章番号>-<小問>.rb
例: ruby-super-intro-lesson/udzura/chapter4/4-2.rb
```

このPRではこのまま修正で大丈夫です！が

* 7章までは提出してしまったので、8章からは合わせてください
* 余裕があればマージ後でもいいので、過去の分の命名規則を直してみてください

2019-06-26 13:05 UTC, S-LEES commented
課題に対するコメントありがとうございます。修正やってみます！
命名規約について全く頭に入ってませんでした、、申し訳ありません。
次回以降は型に則り提出します！

2019-06-29 05:44 UTC, udzura commented
修正はこの `homework_ono` ブランチにプッシュしてください〜

2019-08-26 09:31 UTC, udzura commented
ブランチを間違えたのでPRとしては決して、指摘事項はほかのPRで対応をお願いします！

2019-08-26 09:31 UTC, closed without merging